# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/mediabrix/mediabrix-cocoapods-spec.git'

use_frameworks!

target 'InterstitialOnBootup' do
    pod 'Tapdaq', :podspec => '../Tapdaq.podspec'
    pod 'Tapdaq/AdMob', :podspec => '../Tapdaq.podspec'
    pod 'Tapdaq/AppLovin', :podspec => '../Tapdaq.podspec'
    pod 'Tapdaq/Chartboost', :podspec => '../Tapdaq.podspec'
    pod 'Tapdaq/FAN', :podspec => '../Tapdaq.podspec'
    #pod 'Tapdaq/HyprMx', :podspec => '../Tapdaq.podspec'
    pod 'Tapdaq/InMobi', :podspec => '../Tapdaq.podspec'
    pod 'Tapdaq/Tapjoy', :podspec => '../Tapdaq.podspec'
end

target 'InterstitialOnBootupSwift' do
    pod 'Tapdaq', :podspec => '../Tapdaq.podspec'
    pod 'Tapdaq/AdMob', :podspec => '../Tapdaq.podspec'
    pod 'Tapdaq/AppLovin', :podspec => '../Tapdaq.podspec'
    pod 'Tapdaq/Chartboost', :podspec => '../Tapdaq.podspec'
    pod 'Tapdaq/FAN', :podspec => '../Tapdaq.podspec'
    #pod 'Tapdaq/HyprMx', :podspec => '../Tapdaq.podspec'
    pod 'Tapdaq/InMobi', :podspec => '../Tapdaq.podspec'
    pod 'Tapdaq/Tapjoy', :podspec => '../Tapdaq.podspec'
end

target 'Mediation' do
    pod 'Tapdaq', :podspec => '../Tapdaq.podspec'
    pod 'Tapdaq/AdColony', :podspec => '../Tapdaq.podspec'
    pod 'Tapdaq/AdMob', :podspec => '../Tapdaq.podspec'
    pod 'Tapdaq/AppLovin', :podspec => '../Tapdaq.podspec'
    pod 'Tapdaq/Chartboost', :podspec => '../Tapdaq.podspec'
    pod 'Tapdaq/FAN', :podspec => '../Tapdaq.podspec'
    #pod 'Tapdaq/HyprMx', :podspec => '../Tapdaq.podspec'
    pod 'Tapdaq/InMobi', :podspec => '../Tapdaq.podspec'
    pod 'Tapdaq/IronSource', :podspec => '../Tapdaq.podspec'
    pod 'Tapdaq/Kiip', :podspec => '../Tapdaq.podspec'
    pod 'Tapdaq/MoPub', :podspec => '../Tapdaq.podspec'
    pod 'Tapdaq/Receptiv', :podspec => '../Tapdaq.podspec'
    pod 'Tapdaq/Tapjoy', :podspec => '../Tapdaq.podspec'
    pod 'Tapdaq/UnityAds', :podspec => '../Tapdaq.podspec'
    pod 'Tapdaq/Vungle', :podspec => '../Tapdaq.podspec'
    #pod 'Tapdaq/YouAppi', :podspec => '../Tapdaq.podspec'
    pod 'Tapdaq/ZPlay', :podspec => '../Tapdaq.podspec'
end

target 'MediationSwift' do
    pod 'Tapdaq', :podspec => '../Tapdaq.podspec'
    pod 'Tapdaq/AdColony', :podspec => '../Tapdaq.podspec'
    pod 'Tapdaq/AdMob', :podspec => '../Tapdaq.podspec'
    pod 'Tapdaq/AppLovin', :podspec => '../Tapdaq.podspec'
    pod 'Tapdaq/Chartboost', :podspec => '../Tapdaq.podspec'
    pod 'Tapdaq/FAN', :podspec => '../Tapdaq.podspec'
    #pod 'Tapdaq/HyprMx', :podspec => '../Tapdaq.podspec'
    pod 'Tapdaq/InMobi', :podspec => '../Tapdaq.podspec'
    pod 'Tapdaq/IronSource', :podspec => '../Tapdaq.podspec'
    pod 'Tapdaq/Kiip', :podspec => '../Tapdaq.podspec'
    pod 'Tapdaq/MoPub', :podspec => '../Tapdaq.podspec'
    pod 'Tapdaq/Receptiv', :podspec => '../Tapdaq.podspec'
    pod 'Tapdaq/Tapjoy', :podspec => '../Tapdaq.podspec'
    pod 'Tapdaq/UnityAds', :podspec => '../Tapdaq.podspec'
    pod 'Tapdaq/Vungle', :podspec => '../Tapdaq.podspec'
    #pod 'Tapdaq/YouAppi', :podspec => '../Tapdaq.podspec'
    pod 'Tapdaq/ZPlay', :podspec => '../Tapdaq.podspec'
end

target 'NativeAds' do
    pod 'Tapdaq', :podspec => '../Tapdaq.podspec'
end

target 'NativeAdsSwift' do
    pod 'Tapdaq', :podspec => '../Tapdaq.podspec'
end

target 'NativeAdsMediation' do
    pod 'Tapdaq', :podspec => '../Tapdaq.podspec'
    pod 'Tapdaq/AdMob', :podspec => '../Tapdaq.podspec'
    pod 'Tapdaq/AppLovin', :podspec => '../Tapdaq.podspec'
    pod 'Tapdaq/FAN', :podspec => '../Tapdaq.podspec'
end

target 'NativeAdsMediationSwift' do
    pod 'Tapdaq', :podspec => '../Tapdaq.podspec'
    pod 'Tapdaq/AdMob', :podspec => '../Tapdaq.podspec'
    pod 'Tapdaq/AppLovin', :podspec => '../Tapdaq.podspec'
    pod 'Tapdaq/FAN', :podspec => '../Tapdaq.podspec'
end

target 'MoreApps' do
    pod 'Tapdaq', :podspec => '../Tapdaq.podspec'
end

target 'MoreAppsSwift' do
    pod 'Tapdaq', :podspec => '../Tapdaq.podspec'
end
