# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
# This line is required to be able to install Tapdaq SDK and network adapters
source 'https://github.com/tapdaq/cocoapods.git'
# This line is required to be able to install Receptiv SDK using CocoaPods
source 'https://github.com/mediabrix/mediabrix-cocoapods-spec.git'

use_frameworks!

def sdk_dep
    pod 'Tapdaq', '7.2.50'
end

def interstitial_networks
    pod 'Tapdaq/AdMob', '7.2.50'
    pod 'Tapdaq/AppLovin', '7.2.50'
    pod 'Tapdaq/Chartboost', '7.2.50'
    pod 'Tapdaq/InMobi', '7.2.50'
    pod 'Tapdaq/Kiip', '7.2.50'
    pod 'Tapdaq/YouAppi', '7.2.50' # Uncomment this line if you want to add YouAppi to the sample app. Please note that YouAppi requires a specific Xcode version to run.
end

def native_networks
    pod 'Tapdaq/AdMob', '7.2.50'
    pod 'Tapdaq/AppLovin', '7.2.50'
    pod 'Tapdaq/FAN', '7.2.50'
end

def all_networks
    pod 'Tapdaq/AdColony', '7.2.50'
    pod 'Tapdaq/AdMob', '7.2.50'
    pod 'Tapdaq/AppLovin', '7.2.50'
    pod 'Tapdaq/Chartboost', '7.2.50'
    pod 'Tapdaq/FAN', '7.2.50'
    pod 'Tapdaq/HyprMx', '7.2.50'
    pod 'Tapdaq/InMobi', '7.2.50'
    pod 'Tapdaq/IronSource', '7.2.50'
    pod 'Tapdaq/Kiip', '7.2.50'
    pod 'Tapdaq/MoPub', '7.2.50'
    pod 'Tapdaq/Receptiv', '7.2.50'
    pod 'Tapdaq/Tapjoy', '7.2.50'
    pod 'Tapdaq/UnityAds', '7.2.50'
    pod 'Tapdaq/Vungle', '7.2.50'
    pod 'Tapdaq/YouAppi', '7.2.50' # Uncomment this line if you want to add YouAppi to the sample app. Please note that YouAppi requires a specific Xcode version to run.
    pod 'Tapdaq/ZPlay', '7.2.50'
end

target 'InterstitialOnBootup' do
    sdk_dep
    interstitial_networks
end

target 'InterstitialOnBootupSwift' do
    sdk_dep
    interstitial_networks
end

target 'NativeAdsMediation' do
    sdk_dep
    native_networks
end

target 'NativeAdsMediationSwift' do
    sdk_dep
    native_networks
end

target 'Mediation' do
    sdk_dep
    all_networks
end

target 'MediationSwift' do
    sdk_dep
    all_networks
end

