# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
# This line is required to be able to install Tapdaq SDK and network adapters
source 'https://github.com/tapdaq/cocoapods-specs.git'

use_frameworks!

def sdk_dep_cross_promo
    pod 'Tapdaq', '6.4.1'
end

target 'NativeAds' do
    sdk_dep_cross_promo
end

target 'NativeAdsSwift' do
    sdk_dep_cross_promo
end

target 'MoreApps' do
    sdk_dep_cross_promo
end

target 'MoreAppsSwift' do
    sdk_dep_cross_promo
end
